on: [push, pull_request]

name: Build in Docker

jobs:
  linux:
    name: Docker
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Prepare
        run: |
          sed -i.bak 's|$(GIT) svn info|./.github/workflows/svn-info.sh|' Makefile.in
          ./.github/workflows/wget-recommended.sh
          ./.github/workflows/svn-info.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: .github/workflows/Dockerfile
          tags: |
            ghcr.io/${{github.repository}}:latest
