on: [push, pull_request]

name: Cross platform buildx

jobs:
  linux:
    name: buildx
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ amd64, arm64, riscv64, ppc64le, s390x, arm/v7 ]
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Prepare
        run: |
          sed -i.bak 's|$(GIT) svn info|./.github/workflows/svn-info.sh|' Makefile.in
          ./.github/workflows/svn-info.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          platforms: linux/${{matrix.platform}}
          file: .github/workflows/Dockerfile
          tags: |
            ghcr.io/${{github.repository}}:latest
