on: [push, pull_request]

name: Cross platform buildx

jobs:
  linux:
    name: buildx
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ amd64, riscv64]
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build
        run: |
          docker build --platform linux/${{matrix.platform}} .github/workflows
